### ISSUE TITLE
Check all my repos

### ISSUE THREAD

**Issue by muescha** [github/pages-health-check#10]
The gem should perform the health check on all my repos (like https://github.com/stuartpb/all-my-gh-health )

**Comment by jdennes** [comment]
Thanks for the suggestion. This project is designed to be used as a library for use in other projects (it looks like it's used by the project you linked to, for example), but analysing all repositories in an account isn't really in the scope of what this library is designed to do currently. If this changes in future, we can revisit this as an option.
