### ISSUE TITLE
Releasing a new gem version for Ruby 2.2 warning?

### ISSUE THREAD

**Issue by tarebyte** [github/pages-health-check#11]
Hi There,

Would it be possible to release a new version of `pages-health-check` since @tmm1 fixed the Ruby 2.2 warning (82d4f7f77ba4ea62568ce12bace7b9b31d67d7a5)? I'm currently running into this on my personal project.

Thank you for a great project!

**Comment by jdennes** [comment]
[v0.2.2](https://github.com/github/pages-health-check/releases/tag/v0.2.2) was released.
