### ISSUE TITLE
Integrating Pages health check into the help docs?

### ISSUE THREAD

**Issue by jmarlena** [github/pages-health-check#31]
Hello! :wave: 

I am rewriting some instructions on setting up custom domains for GH Pages sites (github/help-docs/pull/2383) and this feature would be awesome to share with folks! 

Is Pages health check meant for GH Pages users in general or just internal use? 

How does this work exactly?  At first I thought I could just type commands in the command line but then I noticed the README seems to be citing variables not commands. Does this work with IRB? I am confused about how I'd use this without writing a Ruby script. I am trying to gauge how usable this feature is for newbies. 

Excited Pages health check exists! :smiley: 

/cc @github/docs @github/pages

**Comment by benbalter** [comment]
If you have the following in your Gemfile:

```ruby 
gem 'github-pages'
```

Then you'd run the following from your site's directory:

``` 
$ bundle install
$ github-pages health-check
```

And get:

```
Checking domain ben.balter.com...
Everything looks a-okay! :)
```

Or if it's not:

```
Checking domain google.com...
Uh oh. Looks like something's fishy: Domain does not resolve to the GitHub Pages server
```

**Comment by jmarlena** [comment]
Hmmm this works for my local version of the help-docs site but not when I try to reproduce it for another GitHub Pages site.
 

![screen shot 2015-10-22 at 5 00 23 pm](https://cloud.githubusercontent.com/assets/6732600/10681469/6b314ad0-78de-11e5-829c-6f822ef74e0a.png)

I have `github-pages` in my Gemfile but when I try to run `github-pages health-check` after `bundle install` I get this error: 
```
error: 'health-check' is an unrecognized command. options are: 'versions', 'br'.
```

Any thoughts on why this might be?

**Comment by benbalter** [comment]
@jmarlena have you tried `bundle update`?

**Comment by jmarlena** [comment]
@benbalter it works! Thank you.
