### ISSUE TITLE
Typhoeus dependency is outdated (0.7 to 1.3)

### ISSUE THREAD

**Issue by matthewsommer** [github/pages-health-check#76]
The version specified for Typhoeus is very outdated. The latest version is 1.3.

```
s.add_dependency("typhoeus", "~> 0.7")
```

This is causing issues with HTML-Proofer version 3.8.0 that was just released as they added a dependency for Typhoeus 1.3
https://github.com/gjtorikian/html-proofer/commit/065bcb44873a24c611218cc08431c5e7e0dee8ee

**Comment by benbalter** [comment]
@matthewsommer it doesn't appear that there are any breaking changes. If you'd like to submit a pull request to update the Gemspec, and tests pass with the updated dependency, I'd be glad to merge the  change.

**Comment by matthewsommer** [comment]
Hi @benbalter, I submitted a pull request bumping the typhoeus version. The tests were already failing , but this update doesn't add any more new failures so hopefully this is good enough to get merged. I don't know enough about Ruby to understand why the tests are failing but it seems like maybe some DNS fixtures have been modified outside the scope of this code.
